name: Debug Comment
on:
  workflow_dispatch:
permissions:
  issues: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: 1
          comment-id: 5347122552
          body: "updated body test"
          edit-mode: replace
